#ifndef __ERRCODES_H__
#define __ERRCODES_H__

#define SUCCESS 0
#define WRONG_USAGE_ERROR -1
#define SAME_FILENAMES_ERROR -2
#define OPEN_FILE_ERROR -3
#define EMPTY_INPUT_FILE_ERROR -4
#define INVALID_INPUT_FILE_ERROR -5
#define FAILED_MALLOC_ERROR -6
#define MATRICES_SIZES_ERROR -7
#define INCOMPATIBLE_SLAE_ERROR -8

#endif // __ERRCODES_H__
